spring:
  application:
    name: my-cloud-jpa
  jpa:
    database: MYSQL
    generate-ddl: true
    show-sql: true
    open-in-view: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
server:
  context-path: /
  port: 80
logging:
  level:
    root: info
datasource:
  primary:
    url: jdbc:mysql://localhost:3306/shiro
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  secondary:
    url: jdbc:mysql://localhost:3306/shiro
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver