spring:
  application:
    name: my-cloud-sleuth
  sleuth:
    sampler:
      percentage: 0.1
  datasource:
    url: jdbc:mysql://39.105.10.215:3306/activiti
    username: root
    password: zhbroot
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    continueOnError: true
  rabbitmq:
    host: 39.105.10.215
    port: 5672
    username: rabbitmq
    password: zhbrabbitmq
    virtual-host: zhb
    addresses: 39.105.10.215:5672
zipkin:
  storage:
    type: mysql
server:
  context-path: /
  port: 9411
logging:
  level:
    root: info