spring:
  application:
    name: my-cloud-sleuth
  sleuth:
    sampler:
      percentage: 0.1
  datasource:
    url: jdbc:mysql://localhost:3306/sleuth
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    continueOnError: true
  rabbitmq:
    host: localhost
    port: 5672
    username: zhb
    password: hadoop1124
    virtual-host: zhb
    addresses: localhost:5672
    listener:
      acknowledge-mode: auto
eureka:
  client:
    eureka-server-port: 9999
    service-url:
      defaultZone: http://localhost:9999/eureka/
zipkin:
  storage:
    type: mysql
server:
  context-path: /
  port: 9411
logging:
  level:
    root: info