server:
  port: 99
eureka:
  client:
    eureka-server-port: 9999
    service-url:
      defaultZone: http://localhost:9999/eureka/
spring:
  application:
    name: my-cloud-kafka
  datasource:
    url: jdbc:mysql://localhost:3306/shiro
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - 192.168.20.198:9092,192.168.20.221:9092,192.168.20.222:9092
          zk-nodes:
          - 192.168.20.198:2181,192.168.20.221:2181,192.168.20.222:2181
          auto-create-topics: true
          auto-add-partitions: true