server:
  port: 9998
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    hostname: peer2
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: true
    service-url:
      defaultZone: http://peer1:9999/eureka/
spring:
  boot:
    admin:
      url:
      - http://localhost:8090