spring:
  application:
    name: my-cloud-log
  datasource:
    url: jdbc:mysql://localhost:3306/shiro
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 80
logging:
  level:
    com.zhb.cloud: info
  file: my.log
  path: d:/log/