spring:
  application:
    name: my-cloud-ribbon
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    eureka-server-port: 9999
    service-url:
      defaultZone: http://localhost:9999/eureka/
server:
  port: 88