spring:
  application:
    name: my-cloud-feign
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    compression:
      enabled: false
feign:
  compression:
    request:
      min-request-size: 2048
      mime-types:
        - text/xml,application/xml,application/json
server:
  port: 99
logging:
  level:
    root: info
eureka:
  client:
    eureka-server-port: 9999
    service-url:
      defaultZone: http://localhost:9999/eureka/